async def create_user_in_db(name, email, age):
    # Simulate a database insert operation
    user = {
        'id': 2,  # Example ID, in a real scenario this should be auto-generated by the database
        'name': name,
        'email': email,
        'age': age
    }
    return user
